### ISSUE TITLE
如何画出acc曲线

### ISSUE THREAD

**Issue by YangBai1109** [JavisPeng/u_net_liver#1]
你好，请问你一下，你这个网络有可视化的一些程序么？因为没有损失函数曲线什么的。

**Comment by YangBai1109** [comment]
usage: main.py [-h] [--batch_size BATCH_SIZE] [--ckp CKP] action
main.py: error: the following arguments are required: action   
there is a error  how can i solve it ?

**Comment by JavisPeng** [comment]
@PanPan0210 这里你可以使用tensorboard或visdom来可视化
