### ISSUE TITLE
请问一下测试的时候为什么又要重新训练一遍？

### ISSUE THREAD

**Issue by YurongChen1998** [JavisPeng/u_net_liver#4]
python main.py test --ckp=weights_19.pth

**Comment by JavisPeng** [comment]
这里只是加载训练好的权重(ghts_19.pt)，没有重新进行训练，

**Comment by JavisPeng** [comment]
> python main.py test --ckp=weights_19.pth

这里只是加载训练好的权重(ghts_19.pt)，没有重新进行训练，
