### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GengxinXu** [JavisPeng/u_net_liver#6]
When I paste your code
```
python main.py train
```
in the terminal, it works.
But when I implement the `main.py` file in the spyder, it shows the following error:
```
usage: main.py [-h] [--batch_size BATCH_SIZE] [--ckp CKP] action
main.py: error: the following arguments are required: action
An exception has occurred, use %tb to see the full traceback.
```
How to solve this ERROR?

**Comment by JavisPeng** [comment]
I have been using the IDE pycharm maybe you should pass the argment action(train or test) to the main.py. there is a easy way to solve the problem is running the script in the terminal.
